[profile.release]
panic = 'unwind'

[workspace]
members = [
    'pallets/auction',
    'pallets/continuum',
    'pallets/currencies',
    'pallets/estate',
    'pallets/governance',
    'pallets/metaverse',
    'pallets/mining',
    'pallets/nft',
    'pallets/swap',
    'pallets/tokenization',
    'pallets/crowdloan',
    'pallets/economy',
    'traits/*',
    'node',
    'runtime/pioneer',
    'runtime/metaverse',
    'primitives/metaverse',
]
exclude = [
    '/dapps/luckydraw',
    '/dapps/airdrop',
    '/dapps/countrytoken',
    'pallets/oracle',
    'pallet/evm',
    'pallet/evm/*',
    'primitives/evm/',
    'modules/chainsafe',
    'runtime/tewai',
]
