[profile.release]
panic = 'unwind'

[workspace]
members = [
    'pallets/*',
    'traits/*',
    'node',
    'runtime/bitcountry'
    #    'modules/*'
]
exclude = [
    '/dapps/luckydraw',
    '/dapps/airdrop',
    '/dapps/countrytoken',
    'pallets/oracle',
    'modules/chainsafe',
    'runtime/tewai'
    #    'pallets/currencies',
]
