[profile.release]
panic = 'unwind'

[workspace]
members = [
    'pallets/*',
    'traits/*',
    'node',
    'runtime/*',
    'primitives/*',
    'modules/relaychain',
    'modules/support',
]
exclude = [
    'modules/chainsafe',
]

[patch.crates-io]
#ethereum = { git = "https://github.com/justinphamnz/ethereum", branch = "polkadot-v0.9.24", optional = true }
#evm = { git = "https://github.com/justinphamnz/evm", branch = "master", version = "0.33.1", optional = true }
#evm-gasometer = { git = "https://github.com/justinphamnz/evm", branch = "master", version = "0.33.0", optional = true }
#evm-runtime = { git = "https://github.com/justinphamnz/evm", branch = "master", version = "0.33.0", optional = true }
