[profile.release]
panic = 'unwind'

[workspace]
members = [
    'pallets/*',
    'traits/*',
    'node',
    'runtime/bitcountry',
    'runtime/tewai',
]
exclude = [
    '/dapps/luckydraw',
    '/dapps/airdrop',
    '/dapps/countrytoken'
]
