[profile.release]
panic = 'unwind'

[workspace]
members = [
    'pallets/auction',
    'pallets/continuum',
    'pallets/currencies',
    'pallets/estate',
    'pallets/governance',
    'pallets/metaverse',
    'pallets/mining',
    'pallets/nft',
    'pallets/swap',
    'pallets/tokenization',
    'pallets/crowdloan',
    'traits/*',
    'node',
    'runtime/pioneer',
    'runtime/metaverse',
    'primitives/metaverse',
]
exclude = [
    '/dapps/luckydraw',
    '/dapps/airdrop',
    '/dapps/countrytoken',
    'pallets/oracle',
    'pallet/evm',
    'pallet/evm/*',
    'primitives/evm/',
    'modules/chainsafe',
    'runtime/tewai',
]

[patch.crates-io]
ethereum = { git = "https://github.com/AstarNetwork/ethereum", branch = "polkadot-v0.9.13" }
evm = { git = "https://github.com/AstarNetwork/evm", branch = "polkadot-v0.9.13" }
evm-gasometer = { git = "https://github.com/AstarNetwork/evm", branch = "polkadot-v0.9.13" }
evm-runtime = { git = "https://github.com/AstarNetwork/evm", branch = "polkadot-v0.9.13" }