[package]
authors = ['Bit Country <https://github.com/bit-country>']
description = 'Bit Country pallet for unique asset of the country.'
edition = '2018'
homepage = 'https://bit.country'
license = 'Unlicense'
name = 'pallet-unique-asset'
repository = 'https://github.com/bit-country'
version = '2.0.0-rc6'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']


[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
sp-runtime = { version = "2.0.0", default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = "rococo-v1" }
sp-std = { version = "2.0.0", default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = "rococo-v1" }
frame-support = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
frame-system = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
pallet-aura = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1"}
pallet-balances = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
pallet-grandpa = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1"}
pallet-randomness-collective-flip = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1"}
pallet-timestamp = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1"}
pallet-transaction-payment = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1"}
frame-executive = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1"}
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1"}
sp-block-builder = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1"}
sp-consensus-aura = { version = "0.8.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-core = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-inherents = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-offchain = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-session = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1"}
sp-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1"}
sp-version = { version = "2.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1"}
primitives = { package = "bit-country-primitives", path = "../primitives", default-features = false }


# Orml packages
orml-traits = { default-features = false, git = "https://github.com/open-web3-stack/open-runtime-module-library", version = '0.4.0-dev', branch = "sw/rococo-v1" }
orml-currencies = { default-features = false, git = "https://github.com/open-web3-stack/open-runtime-module-library", version = "0.4.0-dev", branch = "sw/rococo-v1" }
orml-tokens = { default-features = false, git = "https://github.com/open-web3-stack/open-runtime-module-library", version = '0.4.0-dev', branch = "sw/rococo-v1" }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-core/std',
    'sp-std/std', 
    'pallet-balances/std',
]
