[package]
authors = ['Bit Country <https://github.com/bit-country>']
description = 'Bit Country pallet for block logic.'
edition = '2018'
homepage = 'https://bit.country'
license = 'Unlicense'
name = 'pallet-estate'
repository = 'https://github.com/bit-country'
version = '2.0.0-rc6'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
serde = { version = "1.0.119", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-system = { version = "3.0.0", default-features = false }
frame-support = { version = "3.0.0", default-features = false }
frame-executive = { version = "3.0.0", default-features = false }
sp-core = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }
sp-version = { version = "3.0.0", default-features = false }
sp-io = { version = "3.0.0", default-features = false }
pallet-collective = {version = "3.0.0", default-features = false}
# local packages
bc-primitives = { path = "../../traits/bc-primitives", default-features = false }
primitives = { package = "bit-country-primitives", path = "../primitives", default-features = false }

[dev-dependencies]
pallet-balances = {version = "3.0.0", default-features = false}

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-io/std',
    'sp-core/std',
    "sp-std/std",
    'bc-primitives/std',
    'primitives/std',
    'pallet-collective/std',
    'pallet-balances/std'
]