[package]
authors = ['BitCountry Developers <https://mvp.studio>']
build = 'build.rs'
description = 'A decentralised world powered by economy.'
edition = '2018'
homepage = 'https://bit.country'
license = 'Unlicense'
name = 'bitcountry-node'
repository = 'https://github.com/bit-country/Bit-Country-Blockchain/'
version = '0.0.1'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "2.0.0" }
serde = { version = "1.0.126", features = ["derive"] }
futures = { version = "0.3.9", features = ["compat"] }
hex-literal = "0.3.1"
log = "0.4.8"
rand = "0.7.2"
structopt = { version = "0.3.8", optional = true }
parking_lot = "0.11.1"

# primitives
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
#sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-transaction-storage-proof = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
# client dependencies
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sc-chain-spec = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-consensus = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sc-network = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-consensus-babe = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-consensus-uncles = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-consensus-aura = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-finality-grandpa = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sc-offchain = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-rpc = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sc-service = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.1" }
sc-executor = { features = ["wasmtime"], git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }
sc-authority-discovery = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
pallet-contracts-rpc = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sp-api = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sp-blockchain = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sp-block-builder = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-rpc-api = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-cli = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
node-rpc = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-consensus-slots = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
frame-benchmarking = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
frame-benchmarking-cli = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-consensus-epochs = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
jsonrpc-core = "15.1.0"
sc-sync-state-rpc = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }
libp2p-wasm-ext = { version = "0.29", features = ["websocket"], optional = true }
# frame dependencies
pallet-indices = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
pallet-contracts = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
# WASM-specific dependencies
primitives = { package = "bit-country-primitives", path = "../pallets/primitives" }
bitcountry-runtime = { version = "2.0.0-rc6", path = "../runtime/bitcountry", optional = true }
tewai-runtime = { version = "2.0.0-rc6", path = "../runtime/tewai", optional = true }

[[bin]]
name = "bitcountry-node"
path = "src/main.rs"

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech//substrate", rev = "852bab073407b65b5e3e461baaa0541c4e0bc3d6" }

[features]
default = ["with-bitcountry-runtime"]
runtime-benchmarks = [
    'bitcountry-runtime/runtime-benchmarks',
    'tewai-runtime/runtime-benchmarks'
]
with-bitcountry-runtime = [
    "bitcountry-runtime",
]
with-tewai-runtime = [
    "tewai-runtime",
]

#TODO change to rococo runtime when merge rococo branch back to master
with-parachain-runtime = [
    "bitcountry-runtime",
]
