[package]
authors = ['Bit.Country Developers <https://github.com/bit-country>']
edition = '2018'
homepage = 'https://bit.country'
license = 'Unlicense'
name = 'tewai-runtime'
description = 'Tewai Public Testnet'
repository = 'https://github.com/bit-country/Bit-Country-Blockchain'
version = '2.0.0-rc6'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# third-party dependencies
codec = { package = 'parity-scale-codec', version = '2.2.0', default-features = false, features = ['derive'] }
serde = { version = '1.0.124', optional = true }
static_assertions = '1.1.0'
hex-literal = { version = '0.3.1' }

# primitives
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
sp-offchain = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
sp-api = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", rev = "91061a7d92" }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
sp-staking = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
sp-keyring = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false, optional = true }
sp-session = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
sp-version = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
sp-npos-elections = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }

# frame dependencies
frame-executive = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false, optional = true }
frame-support = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
frame-election-provider-support = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false, optional = true }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-assets = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-authorship = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-babe = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-bounties = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-collective = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-contracts = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-contracts-primitives = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-contracts-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-democracy = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-election-provider-multi-phase = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-im-online = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-indices = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-identity = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-lottery = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-membership = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-mmr = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-multisig = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-offences = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-offences-benchmarking = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false, optional = true }
pallet-proxy = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-recovery = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-session = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", features = ['historical'], default-features = false }
pallet-session-benchmarking = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false, optional = true }
pallet-staking = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-staking-reward-curve = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-society = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-tips = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-treasury = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-utility = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
pallet-vesting = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }
primitives = { package = 'bit-country-primitives', path = '../../primitives/metaverse', default-features = false }
#chainbridge = { git = 'https://github.com/justinphamnz/chainbridge-substrate', branch = 'master', default-features = false }

# Orml pacakges
orml-currencies = { git = "https://github.com/bit-country/open-runtime-module-library", branch = "master", default-features = false }
orml-tokens = { git = "https://github.com/bit-country/open-runtime-module-library", branch = "master", default-features = false }
orml-traits = { git = "https://github.com/bit-country/open-runtime-module-library", branch = "master", default-features = false }
orml-nft = { git = "https://github.com/bit-country/open-runtime-module-library", branch = "master", default-features = false }

# bit.country dependencies
auction-manager = { package = 'auction-manager', path = '../../traits/auction-manager', version = '2.0.0-rc6', default-features = false }
metaverse = { package = 'pallet-metaverse', path = '../../pallets/metaverse', version = '2.0.0-rc6', default-features = false }
block = { package = 'pallet-block', path = '../../pallets/block', version = '2.0.0-rc6', default-features = false }
tokenization = { package = 'pallet-tokenization', path = '../../pallets/tokenization', version = '2.0.0-rc6', default-features = false }
nft = { package = 'pallet-nft', path = '../../pallets/nft', version = '2.0.0-rc6', default-features = false }
continuum = { package = 'pallet-continuum', path = '../../pallets/continuum', version = '0.0.1', default-features = false }
auction = { package = 'pallet-auction', path = '../../pallets/auction', version = '2.0.0-rc6', default-features = false }
currencies = { package = 'currencies', path = '../../pallets/currencies', version = '2.0.0-rc6', default-features = false }
swap = { package = 'pallet-swap', path = '../../pallets/swap', version = '2.0.0-rc6', default-features = false }
#modules-chainsafe = { package = 'modules-chainsafe', path = '../../modules/chainsafe', version = '0.0.1', default-features = false }
mining = { package = 'pallet-mining', path = '../../pallets/mining', version = '2.0.0-rc6', default-features = false }

[build-dependencies]
substrate-wasm-builder = '4.0.0'

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate", rev = "91061a7d92", default-features = false }

[features]
default = ['std']
with-tracing = ['frame-executive/with-tracing']
std = [
    'sp-authority-discovery/std',
    'pallet-assets/std',
    'pallet-authority-discovery/std',
    'pallet-authorship/std',
    'sp-consensus-babe/std',
    'pallet-babe/std',
    'pallet-balances/std',
    'pallet-bounties/std',
    'sp-block-builder/std',
    'codec/std',
    'pallet-collective/std',
    'pallet-contracts/std',
    'pallet-contracts-primitives/std',
    'pallet-contracts-rpc-runtime-api/std',
    'pallet-democracy/std',
    'pallet-elections-phragmen/std',
    'frame-executive/std',
    'pallet-grandpa/std',
    'pallet-im-online/std',
    'pallet-indices/std',
    'sp-inherents/std',
    'pallet-lottery/std',
    'pallet-membership/std',
    'pallet-mmr/std',
    'pallet-multisig/std',
    'pallet-identity/std',
    'pallet-scheduler/std',
    'sp-offchain/std',
    'pallet-offences/std',
    'pallet-proxy/std',
    'sp-core/std',
    'pallet-randomness-collective-flip/std',
    'sp-std/std',
    'serde',
    'pallet-session/std',
    'sp-api/std',
    'sp-runtime/std',
    'sp-staking/std',
    'pallet-staking/std',
    'sp-keyring',
    'sp-session/std',
    'pallet-sudo/std',
    'frame-support/std',
    'frame-benchmarking/std',
    'frame-system-rpc-runtime-api/std',
    'frame-system/std',
    'pallet-timestamp/std',
    'pallet-tips/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'pallet-transaction-payment/std',
    'pallet-treasury/std',
    'sp-transaction-pool/std',
    'pallet-utility/std',
    'sp-version/std',
    'pallet-society/std',
    'pallet-recovery/std',
    'pallet-vesting/std',
    'auction-manager/std',
    'orml-currencies/std',
    'orml-tokens/std',
    'orml-nft/std',
    'metaverse/std',
    'auction/std',
    'block/std',
    'nft/std',
    'continuum/std',
    'currencies/std',
    'swap/std',
    #    'chainbridge/std',
    #    'modules-chainsafe/std',
    'mining/std',
    'sp-npos-elections/std',
]
runtime-benchmarks = [
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system/runtime-benchmarks',
    'sp-runtime/runtime-benchmarks',
    'pallet-assets/runtime-benchmarks',
    'pallet-babe/runtime-benchmarks',
    'pallet-balances/runtime-benchmarks',
    'pallet-bounties/runtime-benchmarks',
    'pallet-collective/runtime-benchmarks',
    'pallet-contracts/runtime-benchmarks',
    'pallet-democracy/runtime-benchmarks',
    'pallet-elections-phragmen/runtime-benchmarks',
    'pallet-grandpa/runtime-benchmarks',
    'pallet-identity/runtime-benchmarks',
    'pallet-im-online/runtime-benchmarks',
    'pallet-indices/runtime-benchmarks',
    'pallet-lottery/runtime-benchmarks',
    'pallet-mmr/runtime-benchmarks',
    'pallet-multisig/runtime-benchmarks',
    'pallet-proxy/runtime-benchmarks',
    'pallet-scheduler/runtime-benchmarks',
    'pallet-society/runtime-benchmarks',
    'pallet-staking/runtime-benchmarks',
    'pallet-timestamp/runtime-benchmarks',
    'pallet-tips/runtime-benchmarks',
    'pallet-treasury/runtime-benchmarks',
    'pallet-utility/runtime-benchmarks',
    'pallet-vesting/runtime-benchmarks',
    'pallet-offences-benchmarking',
    'pallet-session-benchmarking',
    'frame-system-benchmarking',
    'nft/runtime-benchmarks'
]