[package]
authors = ['Bit Country <https://github.com/bit-country>']
description = 'Bit Country pallet for tokenization logic.'
edition = '2018'
homepage = 'https://bit.country'
license = 'Unlicense'
name = 'social-currencies'
repository = 'https://github.com/bit-country'
version = '2.0.0-rc6'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
serde = { version = "1.0.124", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
pallet-balances = { version = "3.0.0", default-features = false }
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
sp-api = { version = "3.0.0", default-features = false }
sp-io = { version = "3.0.0", default-features = false }
sp-core = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }

# Orml packages
orml-traits = { default-features = false, version = '0.4.0' }

primitives = { package = "bit-country-primitives", path = "../primitives", default-features = false }
bc-country = { path = "../../traits/bc-country", default-features = false }

[dev-dependencies]
#sp-io = { version = "3.0.0", default-features = false }

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-core/std',
    'sp-io/std',
    'sp-std/std',
    'orml-traits/std',
    'primitives/std',
]
