name: Docker build & push

on:
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - master

#   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest

      if: ${{ github.event_name != 'pull_request' }}
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set branch name as env variable
        run: |
          currentbranch=$(echo ${GITHUB_REF##*/})
          echo "running on $currentbranch"
          echo "BRANCH=$currentbranch" >> $GITHUB_ENV
#          echo "REGISTRY_ENDPOINT=jerryjren"
        shell: bash

      - name: Run docker script
        shell: bash
        run: sudo -E scripts/${{ secrets.DOCKER_SCRIPT }}
        working-directory: .
        env:
          TAG: ${{ env.BRANCH }}
          REGISTRY: ${{ secrets.REGISTRY_ENDPOINT }}
