name: Docker and build & push

on:
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - master

#   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set-Up
        run: sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl

      - name: Install Rustup
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source ~/.cargo/env
          rustup default nightly && rustup update
          rustup default nightly-2021-11-07
          rustup target add wasm32-unknown-unknown --toolchain nightly-2021-11-07

      - name: Check Rust version
        run: rustup show
      - name: Check Build
        run: |
          SKIP_WASM_BUILD=1 cargo check --release
      - name: Run all test cases
        run: |
          SKIP_WASM_BUILD= cargo test --all
  build:
      runs-on: ubuntu-latest
      if: ${{ github.event_name != 'pull_request' }}
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set branch name as env variable
        run: |
          currentbranch=$(echo ${GITHUB_REF##*/})
          echo "running on $currentbranch"
          echo "BRANCH=$currentbranch" >> $GITHUB_ENV
          echo "REGISTRY_ENDPOINT=jerryjren"
        shell: bash

      - name: Run docker script
        shell: bash
        run: sudo -E scripts/docker_build_tewai.sh
        working-directory: .
        env:
          TAG: ${{ env.BRANCH }}
          REGISTRY: ${{ env.REGISTRY_ENDPOINT }}